'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Archive, ArrowUpRight, Plus, CircleCheck, Orbit, Pencil, Search, ShieldCheck, Workflow } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { WorkspaceHeading, WorkspaceMetric } from '@/components/workspace/workspace-heading';
import { apiFetch, showError } from '@/lib/api';
import { CampaignEditor } from '@/components/professional/campaign-editor';
import { BRANDS, type Kind, type ProfessionalRecord, type Proposal, type ExternalJob } from '@/lib/professional/schemas';

type ProjectSummary = { id: string; name: string; status: string; context: ProfessionalRecord; gaps: string[]; hasNextAction: boolean; openTasks: number; openWorks: number };
type LegacyKind = 'contact' | 'opportunity' | 'campaign' | 'content';
type Overview = { projects: { items: ProjectSummary[]; nextCursor?: string }; suggestions: { projectId: string; suggestion: string; reason: string; uncertainty: string }[]; counts: { projects: number; works: number; opportunities: number; awaitingReview: number; legacy?: Record<LegacyKind, number> } };
type Goals = { gross: number; invest: number; months: number; revision: number };
const ARCO_LEADS = 'https://arco.oj0nny.com/';
const titles: Record<Kind, string> = { content: 'Pauta de conteúdo', context: 'Projeto profissional', work: 'Próximo passo', contact: 'Empresa ou contato', opportunity: 'Oportunidade', campaign: 'Lista de prospecção', deliverable: 'Entrega para revisão' };
// Three areas around decisions; the CRM lives in Arco Leads. Older contact,
// opportunity, prospecting and content records stay readable, never deleted.
const tabs = [
  { id: 'context', label: 'Visão geral', icon: Orbit, help: 'Seus projetos por marca: objetivo, o que falta saber e o próximo marco.' },
  { id: 'work', label: 'Próximos passos', icon: Workflow, help: 'O que precisa ser feito para avançar, por você ou por um agente. Cada passo pode virar tarefa.' },
  { id: 'review', label: 'Aguardando você', icon: ShieldCheck, help: 'O que o Sirius preparou e só segue com a sua aprovação: escopos, alterações e entregas.' },
  { id: 'legacy', label: 'Registros antigos', icon: Archive, help: 'Contatos, oportunidades, prospecção e pautas criados aqui antes. Ficam só para consulta.' },
] as const;
type Tab = typeof tabs[number]['id'];
const legacyNames: Record<LegacyKind, string> = { contact: 'Contatos', opportunity: 'Oportunidades', campaign: 'Prospecção', content: 'Pautas' };
const stageNames: Record<string, string> = { lead: 'Lead', qualified: 'Qualificado', proposed: 'Proposta enviada', contracted: 'Contratado', invoiced: 'Faturado', received: 'Recebido', lost: 'Perdido' };
const approvalNames: Record<string, string> = { work_scope: 'Escopo de trabalho', record_change: 'Alteração de registro', deliverable: 'Entrega', external_action: 'Ação externa' };
const executionNames: Record<string, string> = { queued: 'Na fila', running: 'Em execução', blocked: 'Bloqueado', failed: 'Falhou', review: 'Pronto para revisão' };
const artifactNames: Record<string, string> = { prospect_list: 'Lista de prospecção', script: 'Roteiro', message_draft: 'Rascunho de mensagem', proposal: 'Proposta', research: 'Pesquisa', content_brief: 'Brief de conteúdo', experiment: 'Experimento' };
const gapNames: Record<string, string> = { objective: 'objetivo', audience: 'público', responsible: 'responsável', expectedOutcome: 'resultado esperado', milestone: 'próximo marco' };
const currency = (amount: unknown) => typeof amount === 'number' ? amount.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) : 'Não informado';

export default function ProfessionalPage() {
  const [overview, setOverview] = useState<Overview | null>(null);
  const [projects, setProjects] = useState<{ id: string; name: string }[]>([]);
  const [tab, setTab] = useState<Tab>('context');
  const [records, setRecords] = useState<ProfessionalRecord[]>([]);
  const [proposals, setProposals] = useState<(Proposal & { approval?: unknown })[]>([]);
  const [jobs, setJobs] = useState<ExternalJob[]>([]);
  const [filterProject, setFilterProject] = useState('');
  const [search, setSearch] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [editor, setEditor] = useState<{ kind: Kind; record?: ProfessionalRecord } | null>(null);
  const [data, setData] = useState<Record<string, unknown>>({});
  const [review, setReview] = useState<(Proposal & { approval?: unknown }) | null>(null);
  const [cursor, setCursor] = useState('0');
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [trail, setTrail] = useState<string[]>([]);
  const [legacyKind, setLegacyKind] = useState<LegacyKind>('contact');
  const [goals, setGoals] = useState<Goals | null>(null);
  const [goalDraft, setGoalDraft] = useState<{ gross: string; invest: string; months: string } | null>(null);

  async function load() {
    try {
      const params = new URLSearchParams({ view: 'overview', ...(tab === 'context' ? { cursor, ...(search ? {search} : {}) } : {}), ...(filterProject ? { projectId: filterProject } : {}) });
      const [summary, allProjects] = await Promise.all([apiFetch<Overview>(`/api/professional?${params}`), apiFetch<{ id: string; name: string }[]>('/api/projects')]);
      setOverview(summary); setProjects(allProjects); if (tab === 'context') setNextCursor(summary.projects.nextCursor || null); setError('');
      const base = { ...(filterProject ? { projectId: filterProject } : {}), ...(search ? { search } : {}), cursor };
      if (tab !== 'context') {
        const result = await apiFetch<{ items: ProfessionalRecord[]; nextCursor: string | null }>(`/api/professional?${new URLSearchParams({ view: 'records', ...base, kind: tab === 'review' ? 'deliverable' : tab === 'legacy' ? legacyKind : tab })}`);
        setRecords(result.items); setNextCursor(result.nextCursor);
      }
      if (tab === 'review' || tab === 'work') {
        const [p, j] = await Promise.all([apiFetch<{ items: (Proposal & { approval?: unknown })[] }>(`/api/professional?${new URLSearchParams({ view: 'proposal', ...base })}`), apiFetch<{ items: ExternalJob[] }>(`/api/professional?${new URLSearchParams({ view: 'jobs', ...base })}`)]);
        setProposals(p.items); setJobs(j.items);
      }
    } catch (failure) { setError(showError(failure)); }
  }
  useEffect(() => { void load(); /* Query is server filtered and paginated. */ // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab, filterProject, search, cursor, legacyKind]);
  useEffect(() => { apiFetch<Goals>('/api/professional/goals').then(setGoals, () => undefined); }, []);
  async function saveGoals() {
    if (!goals || !goalDraft || busy) return; setBusy(true);
    try {
      const next = await apiFetch<Goals>('/api/professional/goals', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ gross: Number(goalDraft.gross) || 0, invest: Number(goalDraft.invest) || 0, months: Number(goalDraft.months) || 6, expectedRevision: goals.revision }) });
      setGoals(next); setGoalDraft(null); toast.success('Metas atualizadas.');
    } catch (failure) { toast.error(showError(failure)); } finally { setBusy(false); }
  }
  const legacyTotal = Object.values(overview?.counts.legacy || {}).reduce((sum, value) => sum + value, 0);
  const visibleTabs = tabs.filter(item => item.id !== 'legacy' || legacyTotal > 0 || tab === 'legacy');
  const current = tabs.find(item => item.id === tab)!;
  const money = (value: number) => value >= 1000 ? `R$ ${(value / 1000).toLocaleString('pt-BR', { maximumFractionDigits: 1 })} mil` : currency(value);

  async function openEditor(kind: Kind, record?: ProfessionalRecord) {
    if (record) {
      try { const detail = await apiFetch<{ items: ProfessionalRecord[] }>(`/api/professional?${new URLSearchParams({view: 'records', id: record.id, projectId: String(record.data.projectId), kind})}`); record = detail.items[0]; if (!record) throw new Error('Registro não encontrado.'); } catch (failure) { toast.error(showError(failure)); return; }
    }
    setEditor({ kind, record }); setData(record ? structuredClone(record.data) : { projectId: filterProject, brandId: overview?.projects.items.find(project => project.id === filterProject)?.context.data.brandId || 'arco-labs' });
  }
  const set = (key: string, value: unknown) => setData(current => ({ ...current, [key]: value }));
  function field(key: string, label: string, multiline = false, type = 'text') {
    const value = data[key];
    return <div key={key} className="space-y-2"><Label htmlFor={`professional-${key}`}>{label}</Label>{multiline ? <Textarea id={`professional-${key}`} value={String(value || '')} onChange={event => set(key, event.target.value)} rows={3} /> : <Input id={`professional-${key}`} type={type} value={String(value ?? '')} onChange={event => set(key, type === 'number' ? event.target.value === '' ? undefined : Number(event.target.value) : event.target.value || undefined)} />}</div>;
  }
  function lines(key: string, label: string) { return <div key={key} className="space-y-2"><Label htmlFor={`professional-${key}`}>{label} · um por linha</Label><Textarea id={`professional-${key}`} rows={3} value={((data[key] || []) as string[]).join('\n')} onChange={event => set(key, event.target.value.split('\n').filter(Boolean))} /></div>; }
  function select(key: string, label: string, options: { value: string; label: string }[]) {
    return <div className="space-y-2"><Label htmlFor={`professional-${key}`}>{label}</Label><select id={`professional-${key}`} className="h-11 w-full rounded-lg border bg-background px-3 text-sm" value={String(data[key] || '')} onChange={event => set(key, event.target.value)}><option value="">Selecionar</option>{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>;
  }
  async function save() {
    if (!editor || busy) return; setBusy(true);
    try {
      const payload = { ...data };
      if (editor.kind === 'context') payload.lastReviewedAt = new Date().toLocaleDateString('en-CA', { timeZone: 'America/Sao_Paulo' });
      await apiFetch('/api/professional', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'save', kind: editor.kind, id: editor.record?.id, expectedRevision: editor.record?.revision || 0, data: payload, idempotencyKey: crypto.randomUUID() }) });
      setEditor(null); await load(); toast.success('Registro salvo com histórico de versão.');
    } catch (failure) { toast.error(showError(failure)); } finally { setBusy(false); }
  }
  async function approve(proposal: Proposal) {
    if (busy) return; setBusy(true);
    try {
      await apiFetch('/api/professional/approval', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ proposalId: proposal.id, revision: proposal.revision, hash: proposal.hash }) });
      await apiFetch('/api/professional', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'apply', id: proposal.id, idempotencyKey: `owner-apply-${proposal.id}` }) });
      setReview(null); await load(); toast.success('Aprovação registrada e alteração aplicada.');
    } catch (failure) { toast.error(showError(failure)); await load(); } finally { setBusy(false); }
  }
  async function proposeDelivery(record: ProfessionalRecord) {
    if (busy) return; setBusy(true);
    try { const proposal = await apiFetch<Proposal>('/api/professional', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'propose', kind: record.kind, id: record.id, expectedRevision: record.revision, approvalType: record.kind === 'work' ? 'work_scope' : 'deliverable', data: record.data, idempotencyKey: `review-${record.id}-v${record.revision}` }) }); setReview(proposal); }
    catch (failure) { toast.error(showError(failure)); } finally { setBusy(false); }
  }

  return <main className="work-page mx-auto max-w-[1600px] px-4 pb-28 pt-6 lg:px-8">
    <WorkspaceHeading eyebrow="Profissional" title="Seu próximo movimento" description="Seus negócios por marca, o que fazer a seguir e o que espera a sua aprovação. Clientes e vendas ficam no Arco Leads." actions={<div className="flex flex-wrap gap-2"><a href={ARCO_LEADS} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center rounded-md border px-4 text-sm font-medium hover:bg-accent">Abrir Arco Leads (CRM)<ArrowUpRight className="ml-2 h-4 w-4" /></a><Button onClick={() => openEditor('context')}><Plus className="mr-2 h-4 w-4" />Adicionar projeto</Button></div>} />
    {error && <div role="alert" className="mb-6 rounded-2xl border border-destructive/30 bg-destructive/10 p-4 text-sm">{error}<p className="mt-2 text-muted-foreground">Esta área exige sua sessão autenticada, inclusive para aprovar. <Link href="/login" className="text-primary underline">Entrar</Link></p><Button variant="outline" className="mt-3" onClick={() => void load()}>Tentar novamente</Button></div>}
    <section className="mb-6 grid gap-3 sm:grid-cols-3" aria-label="Resumo profissional">
      <WorkspaceMetric label="Projetos" value={overview?.counts.projects || 0} detail="Com marca e objetivo associados" />
      <WorkspaceMetric label="Próximos passos" value={overview?.counts.works || 0} detail="Em aberto, seus ou de agentes" />
      <WorkspaceMetric label="Entregas para revisar" value={overview?.counts.awaitingReview || 0} detail="Preparadas para sua aprovação" />
    </section>
    <section className="mb-8 flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-card/40 px-5 py-4" aria-label="Metas do período">
      <div><p className="text-xs font-medium text-primary">Metas · {goals?.months || 6} meses</p><p className="mt-1 text-xs text-muted-foreground">Servem de bússola para decidir. Não entram no saldo nem no realizado.</p></div>
      {goalDraft ? <div className="flex flex-wrap items-end gap-3">
        <div className="space-y-1"><Label htmlFor="goal-gross" className="text-xs">Faturamento bruto (R$)</Label><Input id="goal-gross" type="number" min="0" className="h-9 w-36" value={goalDraft.gross} onChange={event => setGoalDraft({ ...goalDraft, gross: event.target.value })} /></div>
        <div className="space-y-1"><Label htmlFor="goal-invest" className="text-xs">Líquido para investir (R$)</Label><Input id="goal-invest" type="number" min="0" className="h-9 w-36" value={goalDraft.invest} onChange={event => setGoalDraft({ ...goalDraft, invest: event.target.value })} /></div>
        <div className="space-y-1"><Label htmlFor="goal-months" className="text-xs">Meses</Label><Input id="goal-months" type="number" min="1" max="24" className="h-9 w-20" value={goalDraft.months} onChange={event => setGoalDraft({ ...goalDraft, months: event.target.value })} /></div>
        <Button size="sm" variant="outline" disabled={busy} onClick={() => setGoalDraft(null)}>Cancelar</Button><Button size="sm" disabled={busy} onClick={() => void saveGoals()}>Salvar metas</Button>
      </div> : <div className="flex items-center gap-8 text-sm">
        <span><strong className="block font-mono-num text-xl">{goals ? money(goals.gross) : '—'}</strong><span className="text-xs text-muted-foreground">Faturamento bruto</span></span>
        <span><strong className="block font-mono-num text-xl">{goals ? money(goals.invest) : '—'}</strong><span className="text-xs text-muted-foreground">Líquido para investir</span></span>
        <Button size="sm" variant="ghost" disabled={!goals} aria-label="Editar metas" onClick={() => goals && setGoalDraft({ gross: String(goals.gross), invest: String(goals.invest), months: String(goals.months) })}><Pencil className="h-4 w-4" /></Button>
      </div>}
    </section>
    <div className="mb-3 flex flex-wrap items-center justify-between gap-3"><nav aria-label="Áreas profissionais" className="flex max-w-full gap-1 overflow-x-auto rounded-xl border bg-card/40 p-1">{visibleTabs.map(item => <Button key={item.id} variant={tab === item.id ? 'secondary' : 'ghost'} aria-pressed={tab === item.id} className="min-h-11 shrink-0 gap-2" onClick={() => { setTab(item.id); setCursor('0'); setTrail([]); }}><item.icon className="h-4 w-4" />{item.id === 'legacy' ? `${item.label} (${legacyTotal})` : item.label}</Button>)}</nav>{tab === 'work' && <Button variant="outline" onClick={() => openEditor('work')}><Plus className="mr-2 h-4 w-4" />Novo próximo passo</Button>}</div>
    <p className="mb-5 text-sm text-muted-foreground">{current.help}</p>
    {tab === 'legacy' && <div className="mb-5 rounded-2xl border border-primary/30 bg-primary/5 p-4 text-sm"><p>Clientes, oportunidades e prospecção agora ficam no <a href={ARCO_LEADS} target="_blank" rel="noreferrer" className="text-primary underline">Arco Leads</a>, e pautas na tela de <Link href="/conteudo" className="text-primary underline">Conteúdo</Link>. Nada foi apagado: estes registros ficam aqui só para consulta.</p><div className="mt-3 flex flex-wrap gap-2" aria-label="Tipo de registro antigo">{(Object.keys(legacyNames) as LegacyKind[]).map(kind => <Button key={kind} size="sm" variant={legacyKind === kind ? 'secondary' : 'outline'} aria-pressed={legacyKind === kind} onClick={() => { setLegacyKind(kind); setCursor('0'); setTrail([]); }}>{legacyNames[kind]} ({overview?.counts.legacy?.[kind] || 0})</Button>)}</div></div>}
    <div className="mb-6 grid gap-3 sm:grid-cols-[minmax(180px,300px)_1fr]"><select aria-label="Filtrar por projeto" className="h-11 rounded-xl border bg-card px-3 text-sm" value={filterProject} onChange={event => { setFilterProject(event.target.value); setCursor('0'); setTrail([]); }}><option value="">Todos os projetos profissionais</option>{overview?.projects.items.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><Input aria-label="Buscar registros profissionais" className="h-11 pl-9" value={search} onChange={event => { setSearch(event.target.value); setCursor('0'); }} placeholder="Buscar por projeto, passo ou entrega…" /></div></div>
    {tab === 'context' ? <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="grid gap-4 md:grid-cols-2">{overview?.projects.items.filter(project => !search || project.name.toLowerCase().includes(search.toLowerCase())).map(project => <article key={project.id} className="rounded-2xl border bg-card/60 p-6"><p className="text-[11px] uppercase tracking-[.16em] text-primary">{BRANDS.find(brand => brand.id === project.context.data.brandId)?.name} · {BRANDS.find(brand => brand.id === project.context.data.brandId)?.handle}</p><h2 className="mt-3 font-display text-2xl">{project.name}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{String(project.context.data.objective || 'Objetivo ainda não informado.')}</p><div className="mt-5 flex gap-5 text-xs text-muted-foreground"><span>{project.openTasks} {project.openTasks === 1 ? 'tarefa aberta' : 'tarefas abertas'}</span><span>{project.openWorks} {project.openWorks === 1 ? 'próximo passo' : 'próximos passos'}</span></div>{project.gaps.length > 0 && <p className="mt-4 rounded-lg bg-background/50 p-3 text-xs leading-relaxed text-muted-foreground">Falta informar: {project.gaps.map(gap => gapNames[gap] || gap).join(', ')}.</p>}<div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={() => openEditor('context', project.context)}>Editar projeto<ArrowUpRight className="ml-2 h-4 w-4" /></Button><Link href={`/projetos?open=${project.id}`} className="work-action-link">Abrir projeto</Link></div></article>)}{!overview?.projects.items.length && <div className="rounded-2xl border border-dashed p-8 md:col-span-2"><Orbit className="mb-5 h-8 w-8 text-primary" /><h2 className="font-display text-2xl">Comece por um projeto</h2><p className="mt-3 max-w-lg text-sm leading-relaxed text-muted-foreground">Escolha um projeto, a marca e escreva o que quer alcançar. Dá para completar aos poucos; o Sirius mostra o que ainda falta.</p><Button variant="outline" className="mt-6" onClick={() => openEditor('context')}>Adicionar projeto</Button></div>}</div><aside className="rounded-2xl border bg-card/30 p-6"><ShieldCheck className="mb-4 h-6 w-6 text-primary" /><h2 className="font-semibold">Sugestões do Sirius</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">O Sirius aponta o que destravaria cada projeto. Nada muda sem a sua aprovação em “Aguardando você”.</p>{overview?.suggestions.map(suggestion => <div key={suggestion.projectId} className="mt-5 border-t pt-4"><p className="text-sm font-medium">{suggestion.suggestion}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{suggestion.reason} {suggestion.uncertainty}</p></div>)}<p className="mt-6 text-xs leading-relaxed text-muted-foreground">Prioridades: Arco Labs gera caixa com serviços; Arcopass e Ateliê Studio avançam o produto em passos pequenos.</p></aside></div> : <>
      {tab === 'review' && <section className="mb-7"><h2 className="mb-4 font-display text-2xl">Propostas do Sirius</h2><div className="grid gap-3 md:grid-cols-2">{proposals.filter(item => !item.resultId).map(proposal => <article key={proposal.id} className="rounded-2xl border bg-card/60 p-5"><div className="flex items-center justify-between"><span className="text-xs text-primary">{approvalNames[proposal.approvalType] || proposal.approvalType} · versão {proposal.revision}</span><ShieldCheck className="h-4 w-4 text-primary" /></div><h3 className="mt-3 font-semibold">{String(proposal.data.title || proposal.data.name || titles[proposal.kind])}</h3><p className="mt-2 text-xs text-muted-foreground">Preparada por {proposal.author}. Aprovar não envia nada para fora; só registra a decisão.</p><Button variant="outline" className="mt-4" onClick={() => setReview(proposal)}>Revisar e decidir</Button></article>)}</div>{!proposals.some(item => !item.resultId) && <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Nenhuma proposta aguardando sua decisão.</p>}</section>}
      {tab === 'work' && jobs.length > 0 && <section className="mb-6 grid gap-3 md:grid-cols-2">{jobs.map(job => <article key={job.id} className="rounded-xl border border-primary/20 bg-primary/5 p-4"><p className="text-xs font-medium text-primary">Agente · {executionNames[job.execution] || job.execution}</p><p className="mt-2 text-sm">{job.agentId}</p><p className="mt-2 text-xs text-muted-foreground">{job.verifiedSummary || 'Quando o agente terminar, a entrega aparece em “Aguardando você”.'}</p></article>)}</section>}
      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{records.map(record => <article key={record.id} className="min-w-0 rounded-2xl border bg-card/60 p-5"><p className="text-[11px] uppercase tracking-widest text-primary">{BRANDS.find(brand => brand.id === record.data.brandId)?.name}{tab === 'legacy' ? ` · ${legacyNames[record.kind as LegacyKind]}` : ''} · versão {record.revision}</p><h2 className="mt-3 break-words text-base font-semibold">{String(record.data.title || record.data.name)}</h2>{record.kind === 'opportunity' ? <><p className="mt-3 text-sm text-muted-foreground">Etapa: {stageNames[String(record.data.stage)] || String(record.data.stage)}</p><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Bruto estimado</dt><dd>{currency(record.data.grossEstimate)}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Custos estimados</dt><dd>{currency(record.data.costEstimate)}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Parcela do proprietário</dt><dd>{currency(record.data.ownerShareEstimate)}</dd></div></dl><p className="mt-4 text-xs text-muted-foreground">Valores comerciais estimados. Recebimento exige lançamento financeiro separado.</p></> : <p className="mt-3 line-clamp-4 whitespace-pre-wrap text-sm leading-relaxed text-muted-foreground">{String(record.data.nextAction || record.data.objective || record.data.brief || record.data.body || record.data.fit || 'Detalhes ainda não informados.')}</p>}{record.kind === 'contact' && <p className="mt-3 text-xs text-muted-foreground">Verificação: {String(record.data.verification)}{record.data.doNotContact ? ' · Não contatar' : ''}</p>}{tab !== 'legacy' && <div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={() => openEditor(record.kind, record)}>{record.kind === 'deliverable' ? 'Abrir entrega' : 'Editar'}</Button>{record.kind === 'work' && record.data.workType === 'agent' && <Button variant="ghost" disabled={busy} onClick={() => void proposeDelivery(record)}>Pedir aprovação do escopo</Button>}{record.kind === 'deliverable' && <Button variant="ghost" disabled={busy} onClick={() => void proposeDelivery(record)}>Aprovar versão</Button>}</div>}</article>)}</section>
      {!records.length && <div className="rounded-2xl border border-dashed py-14 text-center"><CircleCheck className="mx-auto mb-4 h-7 w-7 text-muted-foreground" /><h2 className="font-display text-2xl">{tab === 'work' ? 'Nenhum próximo passo em aberto' : tab === 'review' ? 'Nenhuma entrega esperando você' : 'Nenhum registro deste tipo'}</h2><p className="mx-auto mt-3 max-w-lg px-5 text-sm text-muted-foreground">{tab === 'work' ? 'Crie um passo pequeno e verificável para algum projeto, ou peça um ao Sirius no Escritório.' : tab === 'review' ? 'Quando o Sirius preparar algo, aparece aqui para você aprovar ou pedir ajustes.' : 'Nada foi criado aqui com este tipo.'}</p></div>}
      <div className="mt-6 flex gap-2">{trail.length > 0 && <Button variant="outline" onClick={() => { setCursor(trail.at(-1)!); setTrail(trail.slice(0, -1)); }}>Página anterior</Button>}{nextCursor && <Button variant="outline" onClick={() => { setTrail([...trail, cursor]); setCursor(nextCursor); }}>Próxima página</Button>}</div>
    </>}
    {tab === 'context' && <div className="mt-6 flex gap-2">{trail.length > 0 && <Button variant="outline" onClick={() => { setCursor(trail.at(-1)!); setTrail(trail.slice(0, -1)); }}>Página anterior</Button>}{nextCursor && <Button variant="outline" onClick={() => { setTrail([...trail, cursor]); setCursor(nextCursor); }}>Próxima página</Button>}</div>}
    <Dialog open={Boolean(editor)} onOpenChange={open => !open && !busy && setEditor(null)}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{editor && titles[editor.kind]}</DialogTitle><DialogDescription>Preencha só o que você sabe; o resto pode ficar em branco. Cada alteração guarda uma versão.</DialogDescription></DialogHeader><div className="space-y-5">
      {select('projectId', 'Projeto associado', (editor?.kind === 'context' ? projects : overview?.projects.items || []).map(project => ({ value: project.id, label: project.name })))}
      {select('brandId', 'Marca', BRANDS.map(brand => ({ value: brand.id, label: `${brand.name} ${brand.handle}` })))}
      {editor?.kind === 'context' ? <>{field('objective', 'Objetivo', true)}{field('audience', 'Público')}{field('responsible', 'Responsável')}{field('milestone', 'Próximo marco')}{field('milestoneDate', 'Prazo do marco', false, 'date')}{lines('unknowns', 'O que ainda não sabemos')}<details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">Oferta, estratégia e recursos</summary><div className="mt-5 space-y-5">{field('problem', 'Problema atendido', true)}{field('currentState', 'Situação atual', true)}{field('maturity', 'Maturidade')}{field('expectedOutcome', 'Resultado esperado', true)}{lines('successCriteria', 'Critérios de sucesso')}{field('offer', 'Oferta', true)}{field('valueProposition', 'Proposta de valor', true)}{select('priority', 'Prioridade', [{ value: 'cash', label: 'Caixa com serviços' }, { value: 'product', label: 'Produto' }, { value: 'maintenance', label: 'Manutenção' }])}{field('priorityReason', 'Motivo da prioridade', true)}{lines('hypotheses', 'Hipóteses')}{lines('blockers', 'Bloqueios')}{lines('restrictions', 'Restrições')}{lines('decisions', 'Decisões pendentes')}{lines('resources', 'Recursos')}</div></details></> : <>
      {field(editor?.kind === 'contact' ? 'name' : 'title', editor?.kind === 'contact' ? 'Empresa ou pessoa' : 'Título')}
      {editor?.kind === 'work' && <>{select('workType', 'Quem executa', [{ value: 'human', label: 'Tarefa humana' }, { value: 'agent', label: 'Trabalho de agente' }, { value: 'decision', label: 'Decisão' }, { value: 'dependency', label: 'Dependência' }])}{field('responsible', 'Responsável')}{field('nextAction', 'Próxima ação concreta', true)}{field('brief', 'Briefing de execução', true)}{field('expectedResult', 'Resultado esperado', true)}{lines('acceptanceCriteria', 'Critérios de aceite')}{field('dueDate', 'Prazo', false, 'date')}{field('effortMinutes', 'Esforço estimado · minutos', false, 'number')}{select('status', 'Situação', [{ value: 'open', label: 'Aberto' }, { value: 'blocked', label: 'Bloqueado' }, { value: 'done', label: 'Concluído por você' }])}<div><Label>O que o agente pode produzir</Label><div className="mt-3 flex flex-wrap gap-3">{['prospect_list', 'script', 'message_draft', 'proposal', 'research', 'content_brief', 'experiment'].map(kind => <label key={kind} className="flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={((data.artifactKinds || []) as string[]).includes(kind)} onChange={event => set('artifactKinds', event.target.checked ? [...((data.artifactKinds || []) as string[]), kind] : ((data.artifactKinds || []) as string[]).filter(item => item !== kind))} />{artifactNames[kind]}</label>)}</div></div></>}
      {editor?.kind === 'contact' && <>{select('entityType', 'Tipo', [{ value: 'company', label: 'Empresa' }, { value: 'person', label: 'Pessoa' }])}{field('segment', 'Segmento')}{field('location', 'Localização')}{field('fit', 'Adequação à oferta', true)}{select('verification', 'Verificação', [{ value: 'unknown', label: 'Desconhecida' }, { value: 'researched', label: 'Pesquisada' }, { value: 'verified', label: 'Verificada' }])}{field('researchedAt', 'Data da pesquisa', false, 'date')}<label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={Boolean(data.doNotContact)} onChange={event => set('doNotContact', event.target.checked)} />Preferência de não contato</label><div><Label>Canais públicos · tipo: valor, um por linha</Label><Textarea className="mt-2" placeholder="website: https://…" value={((data.channels || []) as { type: string; value: string }[]).map(channel => `${channel.type}: ${channel.value}`).join('\n')} onChange={event => set('channels', event.target.value.split('\n').filter(Boolean).map(line => { const [type, ...value] = line.split(':'); return { type: type.trim(), value: value.join(':').trim() }; }))} /></div></>}
      {editor?.kind === 'opportunity' && <>{select('stage', 'Etapa comercial', Object.entries(stageNames).map(([value, label]) => ({ value, label })))}{field('offering', 'Serviço ou produto', true)}{field('contactId', 'ID do contato associado')}{field('grossEstimate', 'Valor bruto estimado', false, 'number')}{field('costEstimate', 'Custos estimados', false, 'number')}{field('ownerShareEstimate', 'Parcela estimada do proprietário', false, 'number')}{field('expectedCloseDate', 'Previsão de fechamento', false, 'date')}{field('expectedReceiptDate', 'Previsão de recebimento', false, 'date')}{field('nextAction', 'Próxima ação', true)}{field('followUpDate', 'Follow-up', false, 'date')}</>}
      {editor?.kind === 'campaign' && <>{field('objective', 'Objetivo', true)}{field('audience', 'Público')}{lines('selectionCriteria', 'Critérios de seleção')}<CampaignEditor data={data} original={editor.record?.data} onChange={set} /><p className="text-xs text-muted-foreground">Sirius pode preparar a lista pesquisada e as versões das mensagens para sua revisão. Preparar não autoriza envio.</p></>}
      {editor?.kind === 'content' && <>{field('body', 'Brief de conteúdo', true)}{select('channel', 'Canal', ['blog', 'youtube', 'instagram', 'tiktok'].map(value => ({value, label:value})))}{field('format', 'Formato')}{field('editorialLine', 'Linha editorial')}{field('audience', 'Público')}{field('objective', 'Objetivo')}{field('cta', 'CTA')}{field('responsible', 'Responsável')}</>}
      {editor?.kind === 'deliverable' && <>{field('objective', 'Objetivo', true)}{field('body', 'Conteúdo da entrega', true)}{field('fileUrl', 'Referência ao arquivo')}{field('verificationSummary', 'Resumo de verificação', true)}{lines('comments', 'Comentários e pedidos de alteração')}<p className="text-xs text-muted-foreground">Salvar mudanças cria nova versão e invalida a aprovação anterior.</p></>}
      </>}
      <details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">Fontes e evidências</summary><p className="mt-3 text-xs text-muted-foreground">Fatos precisam de origem. URLs opcionais; o estado de verificação permanece explícito.</p>{((data[editor?.kind === 'context' ? 'facts' : 'sources'] || []) as { statement: string; url?: string; verification?: string }[]).map((source, index) => <div key={index} className="mt-4 space-y-2"><Input aria-label={`Fato ${index + 1}`} value={source.statement} onChange={event => { const key = editor?.kind === 'context' ? 'facts' : 'sources'; const entries = [...((data[key] || []) as typeof source[])]; entries[index] = { ...source, statement: event.target.value }; set(key, entries); }} /><Input aria-label={`URL da fonte ${index + 1}`} value={source.url || ''} placeholder="https://…" onChange={event => { const key = editor?.kind === 'context' ? 'facts' : 'sources'; const entries = [...((data[key] || []) as typeof source[])]; entries[index] = { ...source, url: event.target.value || undefined }; set(key, entries); }} /></div>)}{['context', 'contact', 'deliverable'].includes(editor?.kind || '') && <Button variant="outline" className="mt-4" onClick={() => { const key = editor?.kind === 'context' ? 'facts' : 'sources'; set(key, [...((data[key] || []) as unknown[]), { statement: '', verification: 'unknown' }]); }}>Adicionar evidência</Button>}</details>
    </div><DialogFooter><Button variant="outline" disabled={busy} onClick={() => setEditor(null)}>Cancelar</Button><Button disabled={busy} onClick={() => void save()}>{busy ? 'Salvando…' : 'Salvar'}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(review)} onOpenChange={open => !open && !busy && setReview(null)}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Revise antes de aprovar</DialogTitle><DialogDescription>Esta decisão vale apenas para a proposta, campos e versão abaixo. Não autoriza envio nem publicação.</DialogDescription></DialogHeader>{review && <><dl className="space-y-2 text-xs text-muted-foreground"><div>Preparada por: {review.author}</div><div>Tipo: {approvalNames[review.approvalType] || review.approvalType} · versão {review.revision}</div><div>Validade: {new Date(review.expiresAt).toLocaleString('pt-BR')}</div></dl><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-words rounded-xl border bg-background/70 p-4 text-xs leading-relaxed">{JSON.stringify(review.data, null, 2)}</pre><p className="text-xs text-muted-foreground">Se precisar alterar os campos, peça uma nova proposta. Uma versão diferente exige outra aprovação.</p></>}<DialogFooter><Button variant="outline" disabled={busy} onClick={() => setReview(null)}>Voltar à revisão</Button><Button disabled={busy || review?.approvalType === 'external_action'} onClick={() => review && void approve(review)}><ShieldCheck className="mr-2 h-4 w-4" />{busy ? 'Registrando…' : 'Aprovar estes campos'}</Button></DialogFooter></DialogContent></Dialog>
  </main>;
}
