import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { canUseMcpTool } from './auth';
import { runMcpToolWithAudit } from './audit';
import { professionalCommand, professionalQuery, runProfessionalBatch } from '@/lib/professional/service';
import { schemas, querySchema, kindSchema, approvalTypeSchema } from '@/lib/professional/schemas';
import { readLedger } from '@/lib/professional/store';
import { fingerprint } from '@/lib/professional/service';

export function registerProfessionalTools(server: McpServer, scopes: string[], clientId = 'legacy') {
  const actor = { id: clientId, human: false };
  function register<S extends z.ZodRawShape>(name: string, description: string, shape: S, execute: (input: z.infer<z.ZodObject<S>>) => Promise<unknown>) {
    if (!canUseMcpTool(name, scopes)) return;
    const concrete: z.ZodRawShape = shape;
    server.registerTool(name, { description, inputSchema: concrete }, async input => runMcpToolWithAudit(name, async () => {
      try { return { content: [{ type: 'text' as const, text: JSON.stringify(await execute(z.object(shape).parse(input))) }] }; }
      catch (error) { return { isError: true, content: [{ type: 'text' as const, text: error instanceof Error ? error.message : 'Operação profissional recusada.' }] }; }
    }, undefined, clientId));
  }
  register('query_professional', 'Consulta apenas projetos associados explicitamente ao espaço profissional. views: overview, project, records, proposal, jobs, stages, diagnostics. Busca/filtros/paginação; lacunas não significam abandono. Sugestões não autorizam gravação. project exige projectId; finanças somente vínculos verificáveis, sem criação ou pagamento.', querySchema.shape, input => professionalQuery(input));
  register('get_professional_schemas', 'Schemas exatos dos registros profissionais. Campos ausentes continuam desconhecidos. Consulte antes de propor; marca nunca inferida do nome. Datas YYYY-MM-DD; responsáveis de agente devem corresponder ao ID da credencial MCP.', {}, async () => ({ contractVersion: '1.0', schemas: Object.fromEntries(Object.entries(schemas).map(([kind, schema]) => [kind, z.toJSONSchema(schema)])) }));
  register('propose_professional_change', 'Prepara campos concretos para revisão humana. Não grava o registro de negócio nem inicia execução. work_scope permite apenas o briefing e os tipos de artefato aprovados; record_change não envia mensagens; deliverable vincula versão atual. external_action não tem executor nesta sessão.', { kind: kindSchema, id: z.string().optional(), expectedRevision: z.number().int().nonnegative().optional(), data: z.record(z.string(), z.unknown()), approvalType: approvalTypeSchema.default('record_change'), idempotencyKey: z.string().min(8).max(200) }, input => professionalCommand({ ...input, action: 'propose' }, actor));
  register('apply_professional_proposal', 'Aplica apenas uma proposta com aprovação humana autenticada vigente, vinculada à versão/hash/campos. Sim genérico não é autorização. Repetir o mesmo ID/chave recupera o recibo. Nenhuma operação financeira, envio ou publicação externa.', { id: z.string().min(1), idempotencyKey: z.string().min(8).max(200) }, input => professionalCommand({ ...input, action: 'apply' }, actor));
  register('submit_professional_artifact', 'Salva uma entrega em Review somente para trabalho com escopo aprovado e atribuído a esta credencial. Corpo/fontes/arquivo e resumo de verificação. Uma revisão cria nova versão e não herda aprovação. Não conclui tarefa nem envia/publica.', { id: z.string().optional(), expectedRevision: z.number().int().nonnegative().optional(), data: schemas.deliverable, idempotencyKey: z.string().min(8).max(200) }, input => professionalCommand({ ...input, kind: 'deliverable', action: 'artifact' }, actor));
  register('report_professional_execution', 'Evento autenticado do contrato Hermes 1.0: jobId, eventId, sequence monotônica, execution, boardId/cardId, verificationSummary. Não presumir webhook nativo. Repetições e snapshots antigos não regridem Review; execução não aprova entrega ou conclui tarefa de negócio.', { data: z.object({ contractVersion: z.literal('1.0'), jobId: z.string(), eventId: z.string(), sequence: z.number().int().positive(), execution: z.enum(['queued', 'running', 'blocked', 'failed', 'review']), boardId: z.string().optional(), cardId: z.string().optional(), verificationSummary: z.string().optional() }).strict(), idempotencyKey: z.string().min(8).max(200) }, input => professionalCommand({ ...input, action: 'event' }, actor));
  register('get_professional_receipt', 'Recupera o resultado observado após timeout pelo mesmo idempotencyKey, sem repetir cegamente. Somente recibos desta credencial. O fingerprint permite verificar se os campos pertencem à mesma intenção.', { idempotencyKey: z.string().min(8).max(200) }, async input => { const ledger = await readLedger(); const receipt = ledger.receipts.find(item => item.actor === clientId && item.key === input.idempotencyKey); return receipt ? { found: true, ...receipt } : { found: false, retrySameKey: true }; });
  register('batch_professional_proposals', 'Prepara até 20 propostas independentes, com resultado/sucesso/falha por item. Não aplica registros nem executa trabalhos. Em falha parcial, repetir somente os mesmos itens com as mesmas chaves.', { proposals: z.array(z.object({ kind: kindSchema, id: z.string().optional(), expectedRevision: z.number().int().nonnegative().optional(), data: z.record(z.string(), z.unknown()), approvalType: approvalTypeSchema.default('record_change'), idempotencyKey: z.string().min(8).max(200) })).min(1).max(20) }, input => runProfessionalBatch(input.proposals.map(proposal => ({ ...proposal, action: 'propose' })), actor));
  register('get_professional_diagnostics', 'Diagnóstico de capacidades e escopos sem chaves, variáveis ou credenciais. Ausência de ferramenta pode indicar escopo, não falta de código.', {}, async () => ({ clientId, scopedProfessionalOnly: scopes.includes('professional:only'), fingerprint: fingerprint([...scopes].sort()), required: ['professional:read', 'professional:propose', 'professional:apply', 'professional:artifact', 'professional:execution'].map(scope => ({ scope, granted: scopes.includes(scope) || scopes.includes('*') })), adapter: 'contract-only', humanApprovalTool: false }));
}
